nodeLinker: hoisted

onlyBuiltDependencies:
  - "@overlayed/electron"
  - electron
  - esbuild

ignoredBuiltDependencies:
  - electron-winstaller

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - "@overlayed/*"
